version: '3.8'

services:
  web:
    build:
      context: web/
    volumes:
      - ./web/:/app:ro
      - static_volume:/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    env_file: [.env]
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - 61261:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static

volumes:
  postgres_data:
  static_volume: