# syntax=docker/dockerfile:1

FROM python:3.10-slim-buster as base
RUN apt update && apt install -y git

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app
CMD gunicorn --workers=1 server:app -b 0.0.0.0:${SERVICE_PORT} --timeout=1200